### ISSUE TITLE
Issue when running pfQuest without pfUI

### ISSUE THREAD

**Issue by ghost** [doorknob6/Inspector#1]
Hi, thanks for this great addon!

I've noticed an issue when running Inspector and pfQuest when pfUI is not enabled. The following error is presented:

_Interface\AddOns\Inspector\inspector.lua:177: attempt to call field 'SkinScrollbar' (a nil value)_

I believe this may be because pfQuest uses pfUI code so inspector is expecting the pfUI.api.SkinScrollbar function
but pfQuest does not include it in "\pfQuest\compat\pfUI.lua".

**Comment by doorknob6** [comment]
Thanks for the report!
This is fixed in the latest version: [e5070e2](https://github.com/doorknob6/Inspector/archive/e5070e2d528a697541bf8faad28b71fdf9081c4f.zip)

**Comment by ghost** [comment]
Thank you very much!
